name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenGL
      run: sudo apt-get install libglew2.1 libglew-dev
    - name: Build
      run: swift build
    - name: Test
      run: swift test
