name: WebAssembly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-WASI:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/swiftwasm/carton
      
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: carton test
